---
language: python
python: "2.7"

sudo: required
dist: trusty

addons:
  hosts:
    - riak.test

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt

install:
  - pip install ansible==2.4
  - gem install inspec

script:
  - ansible-playbook test/integration/default/ansible/default.yml --syntax-check
  - ansible-playbook test/integration/default/ansible/default.yml --connection=local --sudo
  - inspec exec test/integration/default/inspec/default.rb
