---
language: python
python: "2.7"

sudo: required

matrix:
  include:
  - os: ubuntu
    dist: trusty
  - os: centos
    version: 6

addons:
  hosts:
    - riak.test

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "ubuntu" ]]; then
      sudo apt-get update -qq
      sudo apt-get install -qq python-apt
    fi
  - if [[ "$TRAVIS_OS_NAME" == "centos" ]]; then
      sudo yum install python-pip rubygems
    fi

install:
  - pip install ansible==2.4
  - gem install inspec

  - sudo mkdir -p /etc/ansible
  - sudo touch /etc/ansible/hosts
  - "echo -e '[local]\nlocalhost ansible_connection=local' | sudo tee -a /etc/ansible/hosts > /dev/null"

script:
  - ansible-playbook test/integration/default/ansible/default.yml --syntax-check
  - ansible-playbook test/integration/default/ansible/default.yml --connection=local --sudo
  - inspec exec test/integration/default/inspec/default.rb
