---
- name: Install Pre-requisites
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - apt-transport-https

- name: Install JRE
  package:
    name: default-jre
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags: Debian
  when: 'riak_install_java and riak_java_package is undefined'

- name: Add packagecloud key
  apt_key:
    url: https://packagecloud.io/erlang-solutions/riak/gpgkey
    state: present

- name: Add packagecloud repository
  apt_repository:
    repo: deb https://packagecloud.io/erlang-solutions/riak/ubuntu/ trusty main
    state: present
  tags: Debian

- name: Install Riak
  package:
    name: riak
    state: latest

- name: Set the riak ulimit for Debian
  copy:
    src: etc_security_limits.d_riak.conf
    dest: /etc/security/limits.d/riak.conf
  tags: Debian
  when: 'ansible_os_family == "Debian"'

- name: Set the riak ulimit for Ubuntu Trusty
  copy:
    src: etc_default_riak_ulimit
    dest: /etc/default/riak
    owner: riak
    group: riak
  tags: Debian
  when: 'ansible_distribution_release != "xenial" and ansible_distribution_release != "jessie"'

- name: Set the riak ulimit for Ubuntu Xenial
  lineinfile:
    dest: /lib/systemd/system/riak.service
    line: "LimitNOFILE=131072"
    insertafter: "^RuntimeDirectory=riak"
  tags: Debian
  when: 'ansible_distribution_release == "xenial" or ansible_distribution_release == "jessie"'

- name: Reload systemd
  systemd: state=restarted daemon_reload=yes name=riak enabled=yes
  tags: Debian
  when: '(ansible_distribution_release == "xenial" or ansible_distribution_release == "jessie") and (riak_init_system == "system")'
