---
- name: "Install Java & libselinux-python"
  package:
    name: "{{ item }}"
    state: present
  tags: RedHat
  with_items:
    - libselinux-python

- name: Install JRE
  package:
    name: java-1.7.0-openjdk
    state: present
  tags: RedHat
  when: 'riak_install_java and riak_java_package is undefined'

- name: Add packagecloud key
  rpm_key:
    key: https://packagecloud.io/erlang-solutions/riak/gpgkey
    state: present

- name: Add packagecloud repository
  yum_repository:
    name: erlang-solutions_riak
    description: erlang-solutions_riak
    baseurl: https://packagecloud.io/erlang-solutions/riak/el/6/$basearch
    state: present
  tags: Redhat

- name: Set ulimit for open files
  copy:
    src: etc_security_limits.d_riak.conf
    dest: /etc/security/limits.d/riak.conf
    owner: root
    group: root
    mode: 0644

- name: Install Riak for RedHat
  yum:
    name: "{{ riak_package }}"
    state: present
    disable_gpg_check: yes
  tags: RedHat
